### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Boeun-Kim** [wenyh1616/StyleMotion#3]
Hello, I'm interested in your research 👍 
I think the download links of the pretrained weights and the dataset are broken. 
Could you provide it again?
Thank you very much.

**Comment by wenyh1616** [comment]
Thank you for your interest in our work. The download links have been
updated.

Boeun-Kim ***@***.***> 于2023年2月12日周日 00:05写道：

**Comment by Boeun-Kim** [comment]
Thank you for the response.
